baseURL: https://mezounion.org/
languageCode: en-us
title: Mezo Union

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Sustainable Development
    # Hero subtitle (optional)
    subtitle: A new economic model that values people over profit
    # Button text
    buttontext: Start a Revolution
    # Where the main hero button links to
    buttonlink: "strategy"
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - kromo
    - france
    - un
    - systek
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Benefits
    url: /benefits
  - title: How it Works
    url: /how-it-works
  - title: Resources
    sublinks:
    - title: Strategy
      url: /strategy
    - title: Constitution
      url: /constitution
    - title: Code
      url: /code
  - title: Log in
    url: /log-in
  - title: Sign up
    url: /sign-up
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /profile
      - text: Account
        url: /account
      - text: Settings
        url: /settings
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /inbox
      - text: Compose
        url: /compose
    - title: Images
      icon: image
      links:
      - text: Library
        url: /library
      - text: Upload
        url: /upload
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /user-settings
      - text: App settings
        url: /app-settings
  section1:
    title: Change the world
    subtitle: restructure society
    tiles:
    - title: Zero Hunger
      icon: food
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Learn More
    - title: Zero Inequality
      icon: inequality
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Learn More
    - title: Eco-Friendly
      icon: leaf
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Learn More
      buttonText: Learn More
    - title: Lasting Peace
      icon: pigeon
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Learn More
    - title: Worker Freedom
      icon: workers
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Learn More
    - title: Desired Automation
      icon: gear
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Learn More
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: love
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: law
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: peace
  section4:
    title: Directors
    subtitle: The team behind Mezo Union
    clients:
    - name: Tom Guim
      quote: Creator of Mezo and regional director of Africa and Europe.
      job: President
      img: 1
    - name: Jackson Bahm
      quote: Lead Developer and regional director of Asia and Australia.
      job: Vice-President
      img: 2
    - name: Cal Abbo
      quote: Analyst and regional director of North and South America.
      job: Secretary
      img: 3
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/mezounion/mezo
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/mezounion
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    product:
    - text: Discover features
      link: /
    - text: Compare features
      link: /
    - text: Our roadmap
      link: /
    docs:
    - text: Starting the Revolution
      link: https://libcom.org/files/Organise.pdf
    - text: User guides
      link: https://docs.mezounion.org/
    - text: Developers
      link: https://docs.mezounion.org/
    blogroll:
    - text: Constitution
      link: /docs/statuts.pdf
    - text: Offices
      link: /
    - text: Board Members
      link: /
